# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160602_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='match_file_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='match_key',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
