# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160603_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='match_status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='match_file_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='match_key',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='score',
            field=models.CharField(default='', max_length=20),
        ),
    ]
