# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160603_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoForMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(default='', max_length=20)),
                ('file_name', models.CharField(default='', max_length=100)),
                ('match_status', models.SmallIntegerField(default=0)),
                ('match_key', models.CharField(default='', max_length=10)),
                ('match_file_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='match_file_name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='match_key',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='match_status',
        ),
    ]
