# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160604_0635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoForMatch',
        ),
        migrations.AddField(
            model_name='photo',
            name='match_file_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='match_key',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='match_status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
