# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160604_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='match_file_name',
            new_name='matched_id',
        ),
    ]
